modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sableedit"
version = "${version}"
displayName = "SableEdit"
authors = "Malclord"
description = '''

'''
#logoFile = ""

[[dependencies.sableedit]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sableedit]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "sableedit.mixins.json"
