modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sableedit"
version = "${version}"
displayName = "SableEdit"
authors = "${author}"
description = '''
${description}
'''
#logoFile = ""

[[dependencies.sableedit]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sableedit]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.sableedit]]
modId = "sable"
type = "required"
versionRange = "[${sable_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sableedit]]
modId = "worldedit"
type = "required"
versionRange = "[${worldedit_version},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.sableedit]]
modId = "worldeditcui"
type = "optional"
versionRange = "[${worldeditcui_version},)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "sableedit.mixins.json"

[[mixins]]
config = "sableedit.neoforge.mixins.json"
